### ISSUE TITLE
获取MFC程序的按钮时，提示这不是一个MFC window

### ISSUE THREAD

**Issue by ZORfree** [lynnux/xspy#2]
这是整个窗口的信息
****************************************************************************
Tip: Double click to select address，right mouse immediately copy it
target window pid: 0x00000584, thread tid: 0x000002d4
hook thread tid: 0x000002d4

----------Information about ATL/WTL-------------
Address of DWLP_DLGPROC: 0x7718C1CA
Address of GWLP_WNDPROC: 0x004BAE70

----------Information about MFC-------------
MFC version: 90, static linked: true, debug: false
Failed to get address of CWnd::FromHandlePermanent!
****************************************************************************

这是其中一个按钮的信息
****************************************************************************
Tip: Double click to select address，right mouse immediately copy it
target window pid: 0x00000584, thread tid: 0x000002d4
hook thread tid: 0x000002d4

----------Information about ATL/WTL-------------
Address of GWLP_WNDPROC: 0x771A8EBF

----------Information about MFC-------------
It not a MFC window

****************************************************************************

**Comment by lynnux** [comment]
按钮提示不是MFC windows是正常的，本程序是通过HWND调用CWnd::FromHandlePermanent来获取CWnd对象，一般button之类都是没有的
不过上面
```
MFC version: 90, static linked: true, debug: false
Failed to get address of CWnd::FromHandlePermanent!
```
这才算是bug，能上传exe文件上来吗？

**Comment by ZORfree** [comment]
上传到网盘了，一个stb管理工具[下载](https://www.lanzous.com/i383wwd)

**Comment by lynnux** [comment]
@ZORfree 感谢上传，是加了upx壳的原因，已经修复，http://pan.baidu.com/s/1c0rJAm8试试最新版0.4.5

**Comment by ZORfree** [comment]
@lynnux ，试了试，好用！感谢！
